#[derive(Debug, Clone)]
pub enum Token {
    Indent,
    Dedent,
    KeywordBreak,
    KeywordClass,
    KeywordContinue,
    KeywordDef,
    KeywordElse,
    KeywordFor,
    KeywordIf,
    KeywordIn,
    KeywordReturn,
    KeywordWhile,
    Identifier { value: String },
    Number { value: i32 },
    Colon,
    OpeningParenthesis,
    ClosingParenthesis,
    OpeningBrace,
    ClosingBrace,
    OpeningBracket,
    ClosingBracket,
    Comma,
    Plus,
    Minus,
    Asterix,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    EqualEqual,
    NotEqual,
    Arrow,
    NewLine,
}
